version: '3'

services:

  redis:
    image: redis:latest
    container_name: redis_fastapi_db
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data


  # Redis commander (interface gráfica na web para o Redis) configs
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    container_name: "rediscommander"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - "8081:8081"
    depends_on:
      - redis


      
volumes:
  redis-data:

